### ISSUE TITLE
Exposed mongodb+srv credentials

### ISSUE THREAD

**Issue by eth0izzle** [vitormiacri/omnistack-week-9#1]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@cluster0-xiikz.mongodb.net` in file [/backend/src/server.js](https://github.com/vitormiacri/omnistack-week-9/blob/master/backend/src/server.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by vitormiacri** [comment]
Thanks @eth0izzle I updated the file
